spring.application.name=credit_product


spring.datasource.url=jdbc:postgresql://localhost:5432/credit_db
spring.datasource.username=postgres
spring.datasource.password=123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.dynamic-rules.datasource.url=jdbc:postgresql://localhost:5432/dynamic_credit_db
spring.dynamic-rules.datasource.username=postgres
spring.dynamic-rules.datasource.password=123
spring.dynamic-rules.datasource.driver-class-name=org.postgresql.Driver


application.recommendations-db.url=jdbc:h2:file:./transaction;

spring.datasource.driver-class-name=org.postgresql.Driver

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
springdoc.show-actuator=true

springdoc.cache.disabled=true